### ISSUE TITLE
Problème AFontGarde.js sur Chrome 39 + Ubuntu 14.04

### ISSUE THREAD

**Issue by ffoodd** [access42/AccesSlide#35]
Sur cette configuration, AFontGarde se comporte comme si FontAwesome n’était pas chargé et force donc l’utilisation des images de remplacement.

Je n’ai pas pu creuser plus avant ni tester d’autres configurations (sur Firefox 37 + Ubuntu 14.04 tout fonctionne) mais dans l’inspecteur, les ressources FontAwesome sont chargées correctement.

J’essaierai d’apporter plus de précisions dès que possible :)

**Comment by audreymaniez** [comment]
Bonjour, 

Oui nous avions remarqué ce problème, jusqu'à ch38 c'est nickel mais à partir de 39 effectivement, c'est le fallback img qui s'applique. Après avoir parcouru quelques issues similaires sur les font icon, je pense que ça vient de la déclaration de la source des fonts dans les css (ordre des formats etc...), je test rapidement pour y remédier !

Merci pour tes contributions !

**Comment by audreymaniez** [comment]
Hop, 

c'est bon. Après avoir fouillé, le problème résidait dans la 3rd party de afontgarde : typekit/webfontloader
Solution trouvée sur cette issue : https://github.com/typekit/webfontloader/issues/198
C'est en fait la string définie dans le html, qui permet de comparer et de valider ou non le chargement de la font.
Pour FF pas de soucis, mais pour les autres, apparemment, cette chaîne de caractère ne peut pas être personnalisée.
Donc changé : 
`AFontGarde( 'FontAwesome', '\f0d9\f0da');`
En
`AFontGarde( 'FontAwesome', '\uE600\uE601\uE602\uE605');`

Aussi simple qu'un espace en trop ^^

Modification mergée !

**Comment by ffoodd** [comment]
Ah très joli, je n’étais pas prêt de trouver !
Merci :)
